// automatically generated by the FlatBuffers compiler, do not modify

package uci.edu.cs230.toy_cdn.registry.fbs;

public final class RegistrationStatus {
  private RegistrationStatus() { }
  public static final byte OK = 0;
  public static final byte FAILED_INVALID_FORMAT = 1;
  public static final byte FAILED_DUPLICATE = 2;
  public static final byte FAILED_UNKNOWN = 3;

  public static final String[] names = { "OK", "FAILED_INVALID_FORMAT", "FAILED_DUPLICATE", "FAILED_UNKNOWN", };

  public static String name(int e) { return names[e]; }
}

