// automatically generated by the FlatBuffers compiler, do not modify

package uci.edu.cs230.toy_cdn.registry.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class RegistrationResp extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static RegistrationResp getRootAsRegistrationResp(ByteBuffer _bb) { return getRootAsRegistrationResp(_bb, new RegistrationResp()); }
  public static RegistrationResp getRootAsRegistrationResp(ByteBuffer _bb, RegistrationResp obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public RegistrationResp __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte status() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public uci.edu.cs230.toy_cdn.registry.fbs.EndPoint neighbors(int j) { return neighbors(new uci.edu.cs230.toy_cdn.registry.fbs.EndPoint(), j); }
  public uci.edu.cs230.toy_cdn.registry.fbs.EndPoint neighbors(uci.edu.cs230.toy_cdn.registry.fbs.EndPoint obj, int j) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int neighborsLength() { int o = __offset(6); return o != 0 ? __vector_len(o) : 0; }
  public uci.edu.cs230.toy_cdn.registry.fbs.EndPoint.Vector neighborsVector() { return neighborsVector(new uci.edu.cs230.toy_cdn.registry.fbs.EndPoint.Vector()); }
  public uci.edu.cs230.toy_cdn.registry.fbs.EndPoint.Vector neighborsVector(uci.edu.cs230.toy_cdn.registry.fbs.EndPoint.Vector obj) { int o = __offset(6); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createRegistrationResp(FlatBufferBuilder builder,
      byte status,
      int neighborsOffset) {
    builder.startTable(2);
    RegistrationResp.addNeighbors(builder, neighborsOffset);
    RegistrationResp.addStatus(builder, status);
    return RegistrationResp.endRegistrationResp(builder);
  }

  public static void startRegistrationResp(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addStatus(FlatBufferBuilder builder, byte status) { builder.addByte(0, status, 0); }
  public static void addNeighbors(FlatBufferBuilder builder, int neighborsOffset) { builder.addOffset(1, neighborsOffset, 0); }
  public static int createNeighborsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startNeighborsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endRegistrationResp(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishRegistrationRespBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedRegistrationRespBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public RegistrationResp get(int j) { return get(new RegistrationResp(), j); }
    public RegistrationResp get(RegistrationResp obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

