// automatically generated by the FlatBuffers compiler, do not modify

package uci.edu.cs230.toy_cdn.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class EndPoint extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static EndPoint getRootAsEndPoint(ByteBuffer _bb) { return getRootAsEndPoint(_bb, new EndPoint()); }
  public static EndPoint getRootAsEndPoint(ByteBuffer _bb, EndPoint obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public EndPoint __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String ipAddress() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer ipAddressAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer ipAddressInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public int port() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createEndPoint(FlatBufferBuilder builder,
      int ipAddressOffset,
      int port) {
    builder.startTable(2);
    EndPoint.addPort(builder, port);
    EndPoint.addIpAddress(builder, ipAddressOffset);
    return EndPoint.endEndPoint(builder);
  }

  public static void startEndPoint(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addIpAddress(FlatBufferBuilder builder, int ipAddressOffset) { builder.addOffset(0, ipAddressOffset, 0); }
  public static void addPort(FlatBufferBuilder builder, int port) { builder.addInt(1, port, 0); }
  public static int endEndPoint(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public EndPoint get(int j) { return get(new EndPoint(), j); }
    public EndPoint get(EndPoint obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

