// automatically generated by the FlatBuffers compiler, do not modify

package uci.edu.cs230.toy_cdn.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class TraceNode extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public TraceNode __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long nodeId() { return bb.getLong(bb_pos + 0); }
  public int sequence() { return bb.getInt(bb_pos + 8); }

  public static int createTraceNode(FlatBufferBuilder builder, long nodeId, int sequence) {
    builder.prep(8, 16);
    builder.pad(4);
    builder.putInt(sequence);
    builder.putLong(nodeId);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public TraceNode get(int j) { return get(new TraceNode(), j); }
    public TraceNode get(TraceNode obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

